export const colors = {
  'black': '#000000',
  'expandedInfoBGColor': '#EFDDFF',
  'white': '#FFFFFF',
  contactMeBGColor: '#3a60d1',
  contactMeSubmitBtnColorFailure: '#ce4355',
  contactMeSubmitBtnColorSuccess: '#4caf50',
  educationBGColor: '#4e73e8',
  experienceBGColor: '#4e73e8',
  interviewFQSBGColor: '#3a60d1',
  linkCardBGColor: '#FFFFFF',
  linkCardStitching: '#000000',
  lookingForBGColor: '#4e73e8',
  mainStitching: '#FFFFFF',
  pastWorkProjectsBGColor: '#4e73e8',
  profilePicGradient1: '#3a60d1',
  profilePicGradient2: '#c3cfff',
  skillsBGColor: '#4e73e8',
  submitBtnRegular: '#1E45B7',
  textAreaFieldEntry: '#ccc',
  volunteerExpBGColor: '#4e73e8',
  websiteBGGradient1: '#6087ff',
  websiteBGGradient2: '#6087ff',
  websiteBGGradient3: '#6087ff',
};
